version: "3.8"

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cs2_bot
    restart: always
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
      - ./cache:/app/cache
    env_file:
      - .env
    command: supervisord -c /app/supervisord.conf
    ports:
      - "8000:8000"